-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 22:17:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydbase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydbase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbase` DEFAULT CHARACTER SET utf8 ;
USE `mydbase` ;

-- -----------------------------------------------------
-- Table `mydbase`.`place of detection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`place of detection` (
  `id_place` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `city / village` VARCHAR(45) NULL,
  PRIMARY KEY (`id_place`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`storage` (
  `id_storage` INT NOT NULL,
  `square` FLOAT NOT NULL,
  PRIMARY KEY (`id_storage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`collection` (
  `id_collection` INT NOT NULL,
  `number of object in the collection` INT NOT NULL,
  `theme` VARCHAR(45) NULL,
  PRIMARY KEY (`id_collection`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`object recipient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`object recipient` (
  `id_recipient` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_recipient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`item transmitter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`item transmitter` (
  `id_transmitter` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone_number` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_transmitter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`act of receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`act of receipt` (
  `id_act_of_receipt` INT NOT NULL,
  `date of conclusion of the act` DATE NOT NULL,
  `method of receipt` VARCHAR(45) NOT NULL,
  `return date` DATE NULL,
  `id_recipient` INT NOT NULL,
  `id_transmitter` INT NULL,
  PRIMARY KEY (`id_act_of_receipt`),
  INDEX `id_recipient_idx` (`id_recipient` ASC) VISIBLE,
  INDEX `id_transmitter_idx` (`id_transmitter` ASC) VISIBLE,
  CONSTRAINT `id_recipient`
    FOREIGN KEY (`id_recipient`)
    REFERENCES `mydbase`.`object recipient` (`id_recipient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_transmitter`
    FOREIGN KEY (`id_transmitter`)
    REFERENCES `mydbase`.`item transmitter` (`id_transmitter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`museum_object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`museum_object` (
  `іd_object` INT NOT NULL,
  `name of the object` VARCHAR(45) NOT NULL,
  `date of registration` VARCHAR(45) NOT NULL,
  `estimated cost` INT NOT NULL,
  `Possibility of transportation` VARCHAR(3) NOT NULL,
  `Preservation condition` VARCHAR(45) NOT NULL,
  `length` FLOAT NULL,
  `mass` FLOAT NULL,
  `width` FLOAT NULL,
  `іd_collection` INT NULL,
  `id_storage` INT NULL,
  `id_place` INT NULL,
  `id_act_of_receipt` INT NULL,
  PRIMARY KEY (`іd_object`),
  INDEX `id_place_idx` (`id_place` ASC) VISIBLE,
  INDEX `id_storage_idx` (`id_storage` ASC) VISIBLE,
  INDEX `id_collection_idx` (`іd_collection` ASC) VISIBLE,
  INDEX `id_act_of_receipt_idx` (`id_act_of_receipt` ASC) VISIBLE,
  CONSTRAINT `id_place`
    FOREIGN KEY (`id_place`)
    REFERENCES `mydbase`.`place of detection` (`id_place`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_storage`
    FOREIGN KEY (`id_storage`)
    REFERENCES `mydbase`.`storage` (`id_storage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_collection`
    FOREIGN KEY (`іd_collection`)
    REFERENCES `mydbase`.`collection` (`id_collection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_act_of_receipt`
    FOREIGN KEY (`id_act_of_receipt`)
    REFERENCES `mydbase`.`act of receipt` (`id_act_of_receipt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`material characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`material characteristics` (
  `id_material` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `kind` VARCHAR(45) NULL,
  PRIMARY KEY (`id_material`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`material_object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`material_object` (
  `id_material` INT NOT NULL,
  `іd_object` INT NOT NULL,
  INDEX `id_object_idx` (`іd_object` ASC) VISIBLE,
  CONSTRAINT `id_object`
    FOREIGN KEY (`іd_object`)
    REFERENCES `mydbase`.`museum_object` (`іd_object`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_material`
    FOREIGN KEY (`id_material`)
    REFERENCES `mydbase`.`material characteristics` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`hall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`hall` (
  `id_hall` INT NOT NULL,
  `level` INT NOT NULL,
  `square` FLOAT NOT NULL,
  PRIMARY KEY (`id_hall`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`exhibition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`exhibition` (
  `id_exhibition` INT NOT NULL,
  `exhibition name` VARCHAR(45) NULL,
  `start date` DATE NOT NULL,
  `completion date` DATE NOT NULL,
  `id_hall` INT NOT NULL,
  PRIMARY KEY (`id_exhibition`),
  INDEX `id_hall_idx` (`id_hall` ASC) VISIBLE,
  CONSTRAINT `id_hall`
    FOREIGN KEY (`id_hall`)
    REFERENCES `mydbase`.`hall` (`id_hall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbase`.`exposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbase`.`exposition` (
  `id_exhibition` INT NOT NULL,
  `іd_object` INT NOT NULL,
  INDEX `id_object_idx` (`іd_object` ASC) VISIBLE,
  INDEX `id_exhibition_idx` (`id_exhibition` ASC) VISIBLE,
  CONSTRAINT `id_object`
    FOREIGN KEY (`іd_object`)
    REFERENCES `mydbase`.`museum_object` (`іd_object`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_exhibition`
    FOREIGN KEY (`id_exhibition`)
    REFERENCES `mydbase`.`exhibition` (`id_exhibition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
